import { Pinecone } from "@pinecone-database/pinecone";
import dotenv from "dotenv";

dotenv.config();

const pc = new Pinecone({ apiKey: process.env.PINECONE_API_KEY });
// Connect to the specific index created in dashboard
const index = pc.index({ name: "codebase-assistant" });

/**
 * Pushes an array of vector objects into Pinecone.
 * @param {Array} finalizedData - The array generated by our ingestion pipeline.
 */
export async function saveToVectorDB(finalizedData) {
  console.log(
    `\n Preparing to save ${finalizedData.length} vectors to Pinecone...`,
  );

  // Pinecone expects objects in this exact format: { id, values, metadata }
  const pineconeRecords = finalizedData.map((item) => ({
    id: item.id,
    values: item.vector,
    metadata: {
      filePath: item.filePath,
      text: item.text, // We store the actual code text here so the LLM can read it later
    },
  }));

  try {
    // We use an upsert (update/insert).
    // If a chunk ID already exists (e.g., you re-ingest the repo), it overwrites it.
    await index.upsert({records: pineconeRecords});
    console.log(`Successfully saved vectors to Pinecone.`);
  } catch (error) {
    console.error("Failed to save to Pinecone:", error);
  }
}
